name: fooditup
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^1.0.1
  font_awesome_flutter: ^8.0.1
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: ^0.3.0
  flutter_secure_storage: ^3.3.1+1
  http: ^0.11.3+16
  flutter_ibm_watson: ^0.0.2
  image_picker: ^0.6.2+1
  swipedetector: ^1.2.0
  flutter_speed_dial: ^1.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/y1.png
    - assets/profile.png
    - assets/IngredientsSorted.txt

